#remote_theme: artemsheludko/flexible-jekyll
title: Conflict Simulation Group
description: > # this means to ignore newlines until "baseurl:"
  The Conflict Simulation Group at the University of Würzburg

#url: tomjoht.github.io
#   baseurl: /myreponame

url: cosimwue.github.io
baseurl: /cosimwue.github.io

# For testing locally:
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Conflict Simulation Group # add your name
author-img: logo.svg # add your photo
about-author: University of Würzburg # add description
social-twitter: stpielstroem # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: https://github.com/cosimwue # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: pielstroem@biozentrum.uni-wuerzburg.de # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
